branches:
  only:
    - master

skip_tags: true
clone_depth: 1

environment:
  global:
    ASYMPTOTE_HOME: '%PROGRAMFILES(X86)%\\Asymptote'
    MIKTEX_HOME: '%PROGRAMFILES%\\MiKTeX 2.9'
    R_HOME: '%PROGRAMFILES%\\R'
    R_LIBS_USER: '%USERPROFILE%\\R\\library'

install:
  - cinst miktex
  - cinst R.Project --allow-empty-checksums --ia="/DIR=\"%R_HOME%\""
  - curl -fsS -o asymptote-setup.exe http://heanet.dl.sourceforge.net/project/asymptote/2.38/asymptote-2.38-setup.exe
  - asymptote-setup /S "/D=%ASYMPTOTE_HOME%"
  - set PATH=%PATH%;%ASYMPTOTE_HOME%;%R_HOME%\bin;%MIKTEX_HOME%\miktex\bin\x64
  - initexmf --set-config-value=[MPM]AutoInstall=0
  - initexmf "--user-roots=%ASYMPTOTE_HOME%" --update-fndb
  - mpm --install-some=scripts\miktex-packages
  - mkdir -p "${R_LIBS_USER}"
  - Rscript -e "install.packages(c('knitr', 'patchSynctex'), repos = 'http://cran.r-project.org')"
  - ps: Install-Product node 7
  - npm install

test_script:
  - npm test

build: off
