branches:
  only:
    - master

platform:
  - x64

version: 0.11.0-{build}
skip_tags: true
clone_depth: 1

environment:
  global:
    ASYMPTOTE_HOME: '%PROGRAMFILES(X86)%\Asymptote'
    ASYMPTOTE_VERSION: 2.41
    MIKTEX_HOME: '%PROGRAMFILES%\MiKTeX 2.9'
    PYTHON: C:\Python36
    R_HOME: '%PROGRAMFILES%\R'
    R_LIBS_USER: '%USERPROFILE%\R\library'
    STACK_ROOT: C:\StackRoot

cache:
  - '%R_LIBS_USER%'
  - '%LOCALAPPDATA%\pip\Cache'

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - set PATH=%PATH%;C:\Program Files\Git\mingw64\bin;%ASYMPTOTE_HOME%;%MIKTEX_HOME%\miktex\bin\x64;%R_HOME%\bin;%PYTHON%\Scripts
  - curl -LfsS -o asymptote-setup.exe https://downloads.sourceforge.net/project/asymptote/%ASYMPTOTE_VERSION%/asymptote-%ASYMPTOTE_VERSION%-setup.exe
  - asymptote-setup /S "/D=%ASYMPTOTE_HOME%"
  - mkdir "%MIKTEX_HOME%\tex\latex\asymptote"
  - copy "%ASYMPTOTE_HOME%\*.sty" "%MIKTEX_HOME%\tex\latex\asymptote"
  - sh ./scripts/ci-install

before_test:
  - sh ./scripts/ci-before-test

test_script:
  - npm test

build: off
