branches:
  only:
    - master

platform:
  - x64

skip_tags: true
clone_depth: 1

environment:
  global:
    ASYMPTOTE_HOME: '%PROGRAMFILES(X86)%\Asymptote'
    ASYMPTOTE_VERSION: 2.40
    MIKTEX_HOME: '%PROGRAMFILES%\MiKTeX 2.9'
    PYTHON: C:\Python36
    R_HOME: '%PROGRAMFILES%\R'
    R_LIBS_USER: '%USERPROFILE%\R\library'

cache:
  - '%R_LIBS_USER%'

install:
  - set PATH=%PATH%;C:\Program Files\Git\mingw64\bin;%ASYMPTOTE_HOME%;%MIKTEX_HOME%\miktex\bin\x64;%R_HOME%\bin;%PYTHON%\Scripts
  - sh ./scripts/ci-install

before_test:
  - sh ./scripts/ci-before-test

test_script:
  - npm test

build: off
