dist: trusty

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

node_js:
  - node

python:
  - 3.6

os:
  - linux
  - osx

env:
  global:
    - R_LIBS_USER=${HOME}/R/library

cache:
  directories:
    - ${R_LIBS_USER}
    - ${HOME}/.cache/pip

before_cache:
  - rm -f ${HOME}/.cache/pip/log/debug.log

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - asymptote
      - biber
      - feynmf
      - latex-xcolor
      - lhs2tex
      - r-recommended
      - texlive-bibtex-extra
      - texlive-extra-utils
      - texlive-lang-cjk
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-metapost
      - texlive-xetex
      - xindy


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/Library/TeX/texbin:~/Library/Haskell/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -R ~; fi
  - ./scripts/ci-install

before_script:
  - ./scripts/ci-before-test
