dist: trusty

branches:
  only:
    - master

language: node_js

node_js:
  - node

os:
  - linux
  - osx

env:
  global:
    - R_LIBS_USER=${HOME}/R/library

cache:
  directories:
    - ${R_LIBS_USER}

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - asymptote
      - biber
      - feynmf
      - latex-xcolor
      - lhs2tex
      - python-pygments
      - r-recommended
      - texlive-bibtex-extra
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-metapost
      - texlive-xetex

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/Library/TeX/texbin:$PATH; fi
  - ./scripts/install-mac
  - ./scripts/install-r-libs
