dist: trusty
branches:
  only:
    - master
language: node_js
node_js:
  - node
env:
  global:
    - R_LIBS_USER=${HOME}/R/library
cache:
  directories:
    - ${R_LIBS_USER}
addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - asymptote
      - biber
      - feynmf
      - latex-xcolor
      - python-pygments
      - r-recommended
      - texlive-bibtex-extra
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-metapost
      - texlive-xetex
before_install:
  - if ! Rscript -e "library(knitr);library(patchSynctex)" &> /dev/null; then mkdir -p "${R_LIBS_USER}"; Rscript -e "install.packages(c('knitr', 'patchSynctex'), repos = 'http://cran.r-project.org')"; fi
