dist: trusty

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

node_js:
  - node

matrix:
  include:
    - os: linux
    - os: osx
      env: >
        R_LIBS_SITE=/usr/local/lib/R/site-library:/usr/lib/R/site-library
        PATH=/Library/TeX/texbin:~/Library/Haskell/bin:${PATH}

env:
  global:
    - R_LIBS_USER=${HOME}/R/library

cache:
  directories:
    - ${R_LIBS_USER}

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - asymptote
      - biber
      - feynmf
      - latex-xcolor
      - lhs2tex
      - python-pygments
      - r-recommended
      - texlive-bibtex-extra
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-metapost
      - texlive-xetex

before_install:
  - ./scripts/install-mac
  - ./scripts/install-r-libs

before_script:
  - npm run update-dependencies
  - npm run bootstrap
