dist: trusty
branches:
  only:
    - master
language: node_js
node_js:
  - node
addons:
  apt:
    packages:
    - biber
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-bibtex-extra
after_script:
  - cat spec/fixtures/pkg-feynmp.log
  