dist: trusty
branches:
  only:
    - master
language: node_js
node_js:
  - node
addons:
  apt:
    packages:
    - asymptote
    - biber
    - feynmf
    - latex-xcolor
    - python-pygments
    - r-recommended
    - texlive-bibtex-extra
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-metapost
    - texlive-xetex
before_install:
  - Rscript -e "install.packages(c('knitr', 'patchSynctex'), repos = 'http://cran.r-project.org')"
