os:
  - linux
  - osx
dist: trusty
branches:
  only:
    - master
language: node_js
node_js:
  - node
addons:
  apt:
    packages:
    - texlive-latex-base
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-bibtex-extra
    - texlive-metapost
    - biber
    - feynmf
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew tap caskroom/cask && brew cask install mactex; fi;
