branches:
  only:
    - master
language: node_js
node_js:
  - node
addons:
  apt:
    packages:
    - texlive
after_script:
  - cat spec/fixtures/output/biber.log
  - cat spec/fixtures/output/bitex.log
