branches:
  only:
    - master
language: node_js
node_js:
  - node
addons:
  apt:
    packages:
    - texlive
    - texlive-latex-extra
    - biblatex
after_script:
  - cat spec/fixtures/output/bibtex.log
  