dist: trusty

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: r

node_js:
  - node

os:
  - linux
  - osx

env:
  global:
    - NVM_DIR=${HOME}/.nvm

cache: packages

# brew_packages:
#  - ghostscript

pandoc: false

brew_packages:
  - ghostscript

addons:
  apt:
    packages:
      - ghostscript


# addons:
#   apt:
#     sources:
#       - r-packages-trusty
#     packages:
#       - asymptote
#       - biber
#       - feynmf
#       - latex-xcolor
#       - lhs2tex
#       - python-pygments
#       - r-recommended
#       - texlive-bibtex-extra
#       - texlive-latex-base
#       - texlive-latex-extra
#       - texlive-latex-recommended
#       - texlive-metapost
#       - texlive-xetex

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/Library/TeX/texbin:~/Library/Haskell/bin:$PATH; fi
#   - ./scripts/install-mac
#   - ./scripts/install-r-libs

before_script:
  - scripts/travis-install

script:
  - npm test
