// flow-typed signature: 439f644e7976faa4ea7d4e5269bfcad3
// flow-typed version: <<STUB>>/any-shell-escape_v^0.1.1/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'any-shell-escape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'any-shell-escape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'any-shell-escape/shell-escape' {
  declare module.exports: any;
}

// Filename aliases
declare module 'any-shell-escape/shell-escape.js' {
  declare module.exports: $Exports<'any-shell-escape/shell-escape'>;
}
