// flow-typed signature: f6da5412e3a539c1dfc4971ef1ec811b
// flow-typed version: <<STUB>>/command-join_v^2.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'command-join'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'command-join' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'command-join/command-join' {
  declare module.exports: any;
}

declare module 'command-join/test/exec' {
  declare module.exports: any;
}

declare module 'command-join/test/nix.test' {
  declare module.exports: any;
}

declare module 'command-join/test/win.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'command-join/command-join.js' {
  declare module.exports: $Exports<'command-join/command-join'>;
}
declare module 'command-join/test/exec.js' {
  declare module.exports: $Exports<'command-join/test/exec'>;
}
declare module 'command-join/test/nix.test.js' {
  declare module.exports: $Exports<'command-join/test/nix.test'>;
}
declare module 'command-join/test/win.test.js' {
  declare module.exports: $Exports<'command-join/test/win.test'>;
}
