// flow-typed signature: 1425919331779cddeeb977f8ce6a41b8
// flow-typed version: <<STUB>>/fast-glob_v^1.0.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-glob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-glob/out/fglob' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/bash' {
  declare module.exports: any;
}

declare module 'fast-glob/out/providers/readdir' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/io' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/patterns' {
  declare module.exports: any;
}

declare module 'fast-glob/out/utils/task' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-glob/index' {
  declare module.exports: $Exports<'fast-glob'>;
}
declare module 'fast-glob/index.js' {
  declare module.exports: $Exports<'fast-glob'>;
}
declare module 'fast-glob/out/fglob.js' {
  declare module.exports: $Exports<'fast-glob/out/fglob'>;
}
declare module 'fast-glob/out/providers/bash.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/bash'>;
}
declare module 'fast-glob/out/providers/readdir.js' {
  declare module.exports: $Exports<'fast-glob/out/providers/readdir'>;
}
declare module 'fast-glob/out/utils/io.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/io'>;
}
declare module 'fast-glob/out/utils/patterns.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/patterns'>;
}
declare module 'fast-glob/out/utils/task.js' {
  declare module.exports: $Exports<'fast-glob/out/utils/task'>;
}
