// flow-typed signature: 8f165226c3591d98d9afc4dbd4922e60
// flow-typed version: <<STUB>>/micromatch_v^2.3.11/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micromatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'micromatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micromatch/lib/chars' {
  declare module.exports: any;
}

declare module 'micromatch/lib/expand' {
  declare module.exports: any;
}

declare module 'micromatch/lib/glob' {
  declare module.exports: any;
}

declare module 'micromatch/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micromatch/index' {
  declare module.exports: $Exports<'micromatch'>;
}
declare module 'micromatch/index.js' {
  declare module.exports: $Exports<'micromatch'>;
}
declare module 'micromatch/lib/chars.js' {
  declare module.exports: $Exports<'micromatch/lib/chars'>;
}
declare module 'micromatch/lib/expand.js' {
  declare module.exports: $Exports<'micromatch/lib/expand'>;
}
declare module 'micromatch/lib/glob.js' {
  declare module.exports: $Exports<'micromatch/lib/glob'>;
}
declare module 'micromatch/lib/utils.js' {
  declare module.exports: $Exports<'micromatch/lib/utils'>;
}
