// flow-typed signature: cb37a3bd026766dc017812fbf84f51a3
// flow-typed version: <<STUB>>/ouroboros_v^0.0.0/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ouroboros'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ouroboros' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ouroboros/lib/File' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/main' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Ouroboros' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rule' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ApplyOptions' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/AssignJobNames' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/Asymptote' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/Biber' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/BibTeX' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/Clean' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/CopyTargetsToRoot' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/CreateOutputTree' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/DviToPdf' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/DviToPs' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/DviToSvg' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/FindLogFiles' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/GraphDependencies' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/GraphViz' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/Knitr' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/LaTeX' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/LhsToTeX' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/LoadCache' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/MakeGlossaries' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/MakeIndex' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/MetaPost' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseAsymptoteLog' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseBiberLog' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseBibTeXLog' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseLaTeXAuxilary' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseLaTeXFileListing' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseLaTeXLog' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseLaTeXMagic' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseMakeIndexLog' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ParseOptionsFile' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/PatchSyncTeX' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/PdfToPs' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/PsToPdf' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/ReportLogMessages' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/Sage' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/SaveCache' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/Rules/VerifyFileExistance' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/State' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/StateConsumer' {
  declare module.exports: any;
}

declare module 'ouroboros/lib/types' {
  declare module.exports: any;
}

declare module 'ouroboros/spec/FileSpec' {
  declare module.exports: any;
}

declare module 'ouroboros/spec/helpers' {
  declare module.exports: any;
}

declare module 'ouroboros/spec/OuroborosSpec' {
  declare module.exports: any;
}

declare module 'ouroboros/spec/StateSpec' {
  declare module.exports: any;
}

declare module 'ouroboros/src/File' {
  declare module.exports: any;
}

declare module 'ouroboros/src/main' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Ouroboros' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rule' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ApplyOptions' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/AssignJobNames' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/Asymptote' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/Biber' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/BibTeX' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/Clean' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/CopyTargetsToRoot' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/CreateOutputTree' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/DviToPdf' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/DviToPs' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/DviToSvg' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/FindLogFiles' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/GraphDependencies' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/GraphViz' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/Knitr' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/LaTeX' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/LhsToTeX' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/LoadCache' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/MakeGlossaries' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/MakeIndex' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/MetaPost' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseAsymptoteLog' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseBiberLog' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseBibTeXLog' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseLaTeXAuxilary' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseLaTeXFileListing' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseLaTeXLog' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseLaTeXMagic' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseMakeIndexLog' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ParseOptionsFile' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/PatchSyncTeX' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/PdfToPs' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/PsToPdf' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/ReportLogMessages' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/Sage' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/SaveCache' {
  declare module.exports: any;
}

declare module 'ouroboros/src/Rules/VerifyFileExistance' {
  declare module.exports: any;
}

declare module 'ouroboros/src/State' {
  declare module.exports: any;
}

declare module 'ouroboros/src/StateConsumer' {
  declare module.exports: any;
}

declare module 'ouroboros/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ouroboros/lib/File.js' {
  declare module.exports: $Exports<'ouroboros/lib/File'>;
}
declare module 'ouroboros/lib/main.js' {
  declare module.exports: $Exports<'ouroboros/lib/main'>;
}
declare module 'ouroboros/lib/Ouroboros.js' {
  declare module.exports: $Exports<'ouroboros/lib/Ouroboros'>;
}
declare module 'ouroboros/lib/Rule.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rule'>;
}
declare module 'ouroboros/lib/Rules/ApplyOptions.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ApplyOptions'>;
}
declare module 'ouroboros/lib/Rules/AssignJobNames.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/AssignJobNames'>;
}
declare module 'ouroboros/lib/Rules/Asymptote.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/Asymptote'>;
}
declare module 'ouroboros/lib/Rules/Biber.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/Biber'>;
}
declare module 'ouroboros/lib/Rules/BibTeX.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/BibTeX'>;
}
declare module 'ouroboros/lib/Rules/Clean.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/Clean'>;
}
declare module 'ouroboros/lib/Rules/CopyTargetsToRoot.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/CopyTargetsToRoot'>;
}
declare module 'ouroboros/lib/Rules/CreateOutputTree.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/CreateOutputTree'>;
}
declare module 'ouroboros/lib/Rules/DviToPdf.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/DviToPdf'>;
}
declare module 'ouroboros/lib/Rules/DviToPs.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/DviToPs'>;
}
declare module 'ouroboros/lib/Rules/DviToSvg.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/DviToSvg'>;
}
declare module 'ouroboros/lib/Rules/FindLogFiles.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/FindLogFiles'>;
}
declare module 'ouroboros/lib/Rules/GraphDependencies.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/GraphDependencies'>;
}
declare module 'ouroboros/lib/Rules/GraphViz.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/GraphViz'>;
}
declare module 'ouroboros/lib/Rules/Knitr.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/Knitr'>;
}
declare module 'ouroboros/lib/Rules/LaTeX.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/LaTeX'>;
}
declare module 'ouroboros/lib/Rules/LhsToTeX.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/LhsToTeX'>;
}
declare module 'ouroboros/lib/Rules/LoadCache.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/LoadCache'>;
}
declare module 'ouroboros/lib/Rules/MakeGlossaries.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/MakeGlossaries'>;
}
declare module 'ouroboros/lib/Rules/MakeIndex.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/MakeIndex'>;
}
declare module 'ouroboros/lib/Rules/MetaPost.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/MetaPost'>;
}
declare module 'ouroboros/lib/Rules/ParseAsymptoteLog.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseAsymptoteLog'>;
}
declare module 'ouroboros/lib/Rules/ParseBiberLog.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseBiberLog'>;
}
declare module 'ouroboros/lib/Rules/ParseBibTeXLog.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseBibTeXLog'>;
}
declare module 'ouroboros/lib/Rules/ParseLaTeXAuxilary.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseLaTeXAuxilary'>;
}
declare module 'ouroboros/lib/Rules/ParseLaTeXFileListing.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseLaTeXFileListing'>;
}
declare module 'ouroboros/lib/Rules/ParseLaTeXLog.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseLaTeXLog'>;
}
declare module 'ouroboros/lib/Rules/ParseLaTeXMagic.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseLaTeXMagic'>;
}
declare module 'ouroboros/lib/Rules/ParseMakeIndexLog.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseMakeIndexLog'>;
}
declare module 'ouroboros/lib/Rules/ParseOptionsFile.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ParseOptionsFile'>;
}
declare module 'ouroboros/lib/Rules/PatchSyncTeX.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/PatchSyncTeX'>;
}
declare module 'ouroboros/lib/Rules/PdfToPs.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/PdfToPs'>;
}
declare module 'ouroboros/lib/Rules/PsToPdf.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/PsToPdf'>;
}
declare module 'ouroboros/lib/Rules/ReportLogMessages.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/ReportLogMessages'>;
}
declare module 'ouroboros/lib/Rules/Sage.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/Sage'>;
}
declare module 'ouroboros/lib/Rules/SaveCache.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/SaveCache'>;
}
declare module 'ouroboros/lib/Rules/VerifyFileExistance.js' {
  declare module.exports: $Exports<'ouroboros/lib/Rules/VerifyFileExistance'>;
}
declare module 'ouroboros/lib/State.js' {
  declare module.exports: $Exports<'ouroboros/lib/State'>;
}
declare module 'ouroboros/lib/StateConsumer.js' {
  declare module.exports: $Exports<'ouroboros/lib/StateConsumer'>;
}
declare module 'ouroboros/lib/types.js' {
  declare module.exports: $Exports<'ouroboros/lib/types'>;
}
declare module 'ouroboros/spec/FileSpec.js' {
  declare module.exports: $Exports<'ouroboros/spec/FileSpec'>;
}
declare module 'ouroboros/spec/helpers.js' {
  declare module.exports: $Exports<'ouroboros/spec/helpers'>;
}
declare module 'ouroboros/spec/OuroborosSpec.js' {
  declare module.exports: $Exports<'ouroboros/spec/OuroborosSpec'>;
}
declare module 'ouroboros/spec/StateSpec.js' {
  declare module.exports: $Exports<'ouroboros/spec/StateSpec'>;
}
declare module 'ouroboros/src/File.js' {
  declare module.exports: $Exports<'ouroboros/src/File'>;
}
declare module 'ouroboros/src/main.js' {
  declare module.exports: $Exports<'ouroboros/src/main'>;
}
declare module 'ouroboros/src/Ouroboros.js' {
  declare module.exports: $Exports<'ouroboros/src/Ouroboros'>;
}
declare module 'ouroboros/src/Rule.js' {
  declare module.exports: $Exports<'ouroboros/src/Rule'>;
}
declare module 'ouroboros/src/Rules/ApplyOptions.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ApplyOptions'>;
}
declare module 'ouroboros/src/Rules/AssignJobNames.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/AssignJobNames'>;
}
declare module 'ouroboros/src/Rules/Asymptote.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/Asymptote'>;
}
declare module 'ouroboros/src/Rules/Biber.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/Biber'>;
}
declare module 'ouroboros/src/Rules/BibTeX.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/BibTeX'>;
}
declare module 'ouroboros/src/Rules/Clean.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/Clean'>;
}
declare module 'ouroboros/src/Rules/CopyTargetsToRoot.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/CopyTargetsToRoot'>;
}
declare module 'ouroboros/src/Rules/CreateOutputTree.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/CreateOutputTree'>;
}
declare module 'ouroboros/src/Rules/DviToPdf.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/DviToPdf'>;
}
declare module 'ouroboros/src/Rules/DviToPs.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/DviToPs'>;
}
declare module 'ouroboros/src/Rules/DviToSvg.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/DviToSvg'>;
}
declare module 'ouroboros/src/Rules/FindLogFiles.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/FindLogFiles'>;
}
declare module 'ouroboros/src/Rules/GraphDependencies.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/GraphDependencies'>;
}
declare module 'ouroboros/src/Rules/GraphViz.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/GraphViz'>;
}
declare module 'ouroboros/src/Rules/Knitr.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/Knitr'>;
}
declare module 'ouroboros/src/Rules/LaTeX.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/LaTeX'>;
}
declare module 'ouroboros/src/Rules/LhsToTeX.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/LhsToTeX'>;
}
declare module 'ouroboros/src/Rules/LoadCache.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/LoadCache'>;
}
declare module 'ouroboros/src/Rules/MakeGlossaries.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/MakeGlossaries'>;
}
declare module 'ouroboros/src/Rules/MakeIndex.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/MakeIndex'>;
}
declare module 'ouroboros/src/Rules/MetaPost.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/MetaPost'>;
}
declare module 'ouroboros/src/Rules/ParseAsymptoteLog.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseAsymptoteLog'>;
}
declare module 'ouroboros/src/Rules/ParseBiberLog.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseBiberLog'>;
}
declare module 'ouroboros/src/Rules/ParseBibTeXLog.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseBibTeXLog'>;
}
declare module 'ouroboros/src/Rules/ParseLaTeXAuxilary.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseLaTeXAuxilary'>;
}
declare module 'ouroboros/src/Rules/ParseLaTeXFileListing.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseLaTeXFileListing'>;
}
declare module 'ouroboros/src/Rules/ParseLaTeXLog.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseLaTeXLog'>;
}
declare module 'ouroboros/src/Rules/ParseLaTeXMagic.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseLaTeXMagic'>;
}
declare module 'ouroboros/src/Rules/ParseMakeIndexLog.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseMakeIndexLog'>;
}
declare module 'ouroboros/src/Rules/ParseOptionsFile.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ParseOptionsFile'>;
}
declare module 'ouroboros/src/Rules/PatchSyncTeX.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/PatchSyncTeX'>;
}
declare module 'ouroboros/src/Rules/PdfToPs.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/PdfToPs'>;
}
declare module 'ouroboros/src/Rules/PsToPdf.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/PsToPdf'>;
}
declare module 'ouroboros/src/Rules/ReportLogMessages.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/ReportLogMessages'>;
}
declare module 'ouroboros/src/Rules/Sage.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/Sage'>;
}
declare module 'ouroboros/src/Rules/SaveCache.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/SaveCache'>;
}
declare module 'ouroboros/src/Rules/VerifyFileExistance.js' {
  declare module.exports: $Exports<'ouroboros/src/Rules/VerifyFileExistance'>;
}
declare module 'ouroboros/src/State.js' {
  declare module.exports: $Exports<'ouroboros/src/State'>;
}
declare module 'ouroboros/src/StateConsumer.js' {
  declare module.exports: $Exports<'ouroboros/src/StateConsumer'>;
}
declare module 'ouroboros/src/types.js' {
  declare module.exports: $Exports<'ouroboros/src/types'>;
}
