// flow-typed signature: 261a099e2bd7a87ace882348a8af46e1
// flow-typed version: <<STUB>>/readdir-enhanced_v^1.4.5/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'readdir-enhanced'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'readdir-enhanced' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'readdir-enhanced/lib/async/for-each' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/async/fs' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/async/index' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/async/promise' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/directory-reader' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/index' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/normalize-options' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/once' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/stat' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/stream/index' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/sync/for-each' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/sync/fs' {
  declare module.exports: any;
}

declare module 'readdir-enhanced/lib/sync/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'readdir-enhanced/lib/async/for-each.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/async/for-each'>;
}
declare module 'readdir-enhanced/lib/async/fs.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/async/fs'>;
}
declare module 'readdir-enhanced/lib/async/index.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/async/index'>;
}
declare module 'readdir-enhanced/lib/async/promise.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/async/promise'>;
}
declare module 'readdir-enhanced/lib/directory-reader.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/directory-reader'>;
}
declare module 'readdir-enhanced/lib/index.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/index'>;
}
declare module 'readdir-enhanced/lib/normalize-options.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/normalize-options'>;
}
declare module 'readdir-enhanced/lib/once.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/once'>;
}
declare module 'readdir-enhanced/lib/stat.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/stat'>;
}
declare module 'readdir-enhanced/lib/stream/index.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/stream/index'>;
}
declare module 'readdir-enhanced/lib/sync/for-each.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/sync/for-each'>;
}
declare module 'readdir-enhanced/lib/sync/fs.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/sync/fs'>;
}
declare module 'readdir-enhanced/lib/sync/index.js' {
  declare module.exports: $Exports<'readdir-enhanced/lib/sync/index'>;
}
