/* @flow */

export type JobOptions = {
  [name: string]: string | Array<string>,
  bibtexEngine: "bibtex" | "bibtex8" | "bibtexu" | "pbibtex" | "upbibtex",
  check?: Array<string>,
  cleanPatterns: Array<string>,
  copyTargetsToRoot?: boolean,
  disableRules: Array<string>,
  dviToPdfEngine: "dvipdfm" | "xdvipdfmx" | "dvipdfmx",
  engine: string,
  epstopdfBoundingBox: "default" | "exact" | "hires",
  epstopdfOutputPath: string,
  epstopdfRestricted?: boolean,
  filePath?: string,
  ignoreCache?: boolean,
  ignoreUserOptions?: boolean,
  indexAutomaticRanges: boolean,
  indexCompressBlanks?: boolean,
  indexDictionary?: string,
  indexEngine: "makeindex" | "mendex" | "texindy" | "upmendex",
  indexForceKanji?: boolean,
  indexLogPath?: string,
  indexOrdering: "word" | "letter",
  indexOutputPath?: string,
  indexSorting: "default" | "german" | "thai" | "locale",
  indexStartPage?: string,
  indexStyle?: string,
  intermediatePostScript?: boolean,
  jobName?: string,
  kanji?: "euc" | "jis" | "sjis" | "uptex" | "utf8",
  kanjiInternal?: "euc" | "sjis" | "uptex" | "utf8",
  knitrConcordance: boolean,
  knitrOutputPath: string,
  lhs2texStyle: "poly" | "math" | "newCode" | "code" | "typewriter" | "verbatim",
  literateAgdaEngine: "agda" | "lhs2TeX" | "none",
  literateHaskellEngine: "lhs2TeX" | "none",
  outputDirectory?: string,
  outputFormat: "dvi" | "pdf" | "ps" | "svg",
  phaseCycles: number,
  pweaveCacheDirectory: string,
  pweaveDocumentationMode?: boolean,
  pweaveFigureDirectory: string,
  pweaveFigureFormat: "auto" | "pdf" | "eps" | "svg",
  pweaveOutputFormat: "tex" | "texminted" | "texpweave" | "texpygments",
  pweaveOutputPath: string,
  severity: "info" | "warning" | "error",
  shellEscape?: false | "disabled" | "restricted" | "enabled" | true,
  synctex?: boolean
}

export type StateOptions = {
  jobs?: { [job: string]: JobOptions },
  jobNames?: Array<string>,
  [name: string]: string | Array<string>,
  bibtexEngine: "bibtex" | "bibtex8" | "bibtexu" | "pbibtex" | "upbibtex",
  check?: Array<string>,
  cleanPatterns: Array<string>,
  copyTargetsToRoot?: boolean,
  disableRules: Array<string>,
  dviToPdfEngine: "dvipdfm" | "xdvipdfmx" | "dvipdfmx",
  engine: string,
  epstopdfBoundingBox: "default" | "exact" | "hires",
  epstopdfOutputPath: string,
  epstopdfRestricted?: boolean,
  filePath?: string,
  ignoreCache?: boolean,
  ignoreUserOptions?: boolean,
  indexAutomaticRanges: boolean,
  indexCompressBlanks?: boolean,
  indexDictionary?: string,
  indexEngine: "makeindex" | "mendex" | "texindy" | "upmendex",
  indexForceKanji?: boolean,
  indexLogPath?: string,
  indexOrdering: "word" | "letter",
  indexOutputPath?: string,
  indexSorting: "default" | "german" | "thai" | "locale",
  indexStartPage?: string,
  indexStyle?: string,
  intermediatePostScript?: boolean,
  jobName?: string,
  kanji?: "euc" | "jis" | "sjis" | "uptex" | "utf8",
  kanjiInternal?: "euc" | "sjis" | "uptex" | "utf8",
  knitrConcordance: boolean,
  knitrOutputPath: string,
  lhs2texStyle: "poly" | "math" | "newCode" | "code" | "typewriter" | "verbatim",
  literateAgdaEngine: "agda" | "lhs2TeX" | "none",
  literateHaskellEngine: "lhs2TeX" | "none",
  outputDirectory?: string,
  outputFormat: "dvi" | "pdf" | "ps" | "svg",
  phaseCycles: number,
  pweaveCacheDirectory: string,
  pweaveDocumentationMode?: boolean,
  pweaveFigureDirectory: string,
  pweaveFigureFormat: "auto" | "pdf" | "eps" | "svg",
  pweaveOutputFormat: "tex" | "texminted" | "texpweave" | "texpygments",
  pweaveOutputPath: string,
  severity: "info" | "warning" | "error",
  shellEscape?: false | "disabled" | "restricted" | "enabled" | true,
  synctex?: boolean
}

export interface OptionInterface {
  [name: string]: string | Array<string>,
  bibtexEngine: "bibtex" | "bibtex8" | "bibtexu" | "pbibtex" | "upbibtex",
  check?: Array<string>,
  cleanPatterns: Array<string>,
  copyTargetsToRoot?: boolean,
  disableRules: Array<string>,
  dviToPdfEngine: "dvipdfm" | "xdvipdfmx" | "dvipdfmx",
  engine: string,
  epstopdfBoundingBox: "default" | "exact" | "hires",
  epstopdfOutputPath: string,
  epstopdfRestricted?: boolean,
  filePath?: string,
  ignoreCache?: boolean,
  ignoreUserOptions?: boolean,
  indexAutomaticRanges: boolean,
  indexCompressBlanks?: boolean,
  indexDictionary?: string,
  indexEngine: "makeindex" | "mendex" | "texindy" | "upmendex",
  indexForceKanji?: boolean,
  indexLogPath?: string,
  indexOrdering: "word" | "letter",
  indexOutputPath?: string,
  indexSorting: "default" | "german" | "thai" | "locale",
  indexStartPage?: string,
  indexStyle?: string,
  intermediatePostScript?: boolean,
  jobName?: string,
  kanji?: "euc" | "jis" | "sjis" | "uptex" | "utf8",
  kanjiInternal?: "euc" | "sjis" | "uptex" | "utf8",
  knitrConcordance: boolean,
  knitrOutputPath: string,
  lhs2texStyle: "poly" | "math" | "newCode" | "code" | "typewriter" | "verbatim",
  literateAgdaEngine: "agda" | "lhs2TeX" | "none",
  literateHaskellEngine: "lhs2TeX" | "none",
  outputDirectory?: string,
  outputFormat: "dvi" | "pdf" | "ps" | "svg",
  phaseCycles: number,
  pweaveCacheDirectory: string,
  pweaveDocumentationMode?: boolean,
  pweaveFigureDirectory: string,
  pweaveFigureFormat: "auto" | "pdf" | "eps" | "svg",
  pweaveOutputFormat: "tex" | "texminted" | "texpweave" | "texpygments",
  pweaveOutputPath: string,
  severity: "info" | "warning" | "error",
  shellEscape?: false | "disabled" | "restricted" | "enabled" | true,
  synctex?: boolean
}

export const DEFAULT_OPTIONS = {}
