#!/usr/bin/env bash

shopt -s nocasematch

echo Bootstrapping...
if [[ "${APPVEYOR:-}" == true ]]; then
  npm run bootstrap -- --scope=@dicy/types
  npm run bootstrap -- --scope=@dicy/core
  npm run bootstrap -- --scope=@dicy/server
fi

npm run bootstrap
