#!/usr/bin/env bash

shopt -s nocasematch

echo Updating package dependencies...
npm run update-dependencies

echo Bootstrapping...
if [[ "${APPVEYOR:-}" == true ]]; then
  npm run bootstrap -- --scope=@dicy/core
  npm run bootstrap -- --scope=@dicy/server
fi

npm run bootstrap
