#!/usr/bin/env bash

shopt -s nocasematch

if [[ "${APPVEYOR:-}" == true ]]; then
  echo Installing node...
  PowerShell -Command Install-Product node 10 x64

  # TODO: Remove when 'R.Project' package adds it as a dependency.
  echo Installing chocolatey-core.extension...
  choco install chocolatey-core.extension

  echo Installing GhostScript...
  cinst ghostscript

  echo Installing R...
  cinst R.Project --allow-empty-checksums --ia="/DIR=\"${R_HOME}\""

  echo Installing MikTeX...
  curl -fsSL -o basic-miktex-x64.exe http://mirrors.ctan.org/tex-archive/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.6813-x64.exe
  ./basic-miktex-x64 --unattended --shared

  echo Installing TeX packages...
  initexmf --admin --set-config-value=[MPM]AutoInstall=0
  mpm --admin --verbose --update-db --update --install-some=scripts\\miktex-packages
  pdflatex -version

  echo Installing package dependencies...
  npm install -g lerna@2.9.0
  npm install
elif [[ "${TRAVIS_OS_NAME:-}" == "osx" ]]; then
  export PATH=/Library/TeX/texbin:~/Library/Haskell/bin:$PATH
  export CC=gcc-7
  export CXX=g++-7

  echo Updating homebrew...
  brew update

  echo Installing GCC
  rm /usr/local/include/c++
  brew install gcc

  echo Installing Python 3...
  brew upgrade python
  # virtualenv venv -p python3
  # source venv/bin/activate

  echo Installing GhostScript...
  brew install ghostscript

  echo Installing Agda and lhs2TeX...
  wget https://haskell.org/platform/download/8.4.3/Haskell%20Platform%208.4.3%20Core%2064bit-signed.pkg
  sudo installer -pkg "Haskell Platform 8.4.3 Core 64bit-signed.pkg" -target /
  # brew cask install haskell-platform
  stack update
  sudo cabal install lhs2tex

  echo Installing R...
  # brew tap homebrew/science
  brew install r

  echo Installing MacTeX...
  wget http://tug.org/cgi-bin/mactex-download/BasicTeX.pkg
  sudo installer -pkg BasicTeX.pkg -target /

  echo Installing TeX packages...
  sudo tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
  sudo tlmgr update --self
  sudo tlmgr update --all
  cat "scripts/mactex-packages" | xargs sudo tlmgr install
fi

echo Installing Python libraries...
PIP_MODULES=(Pygments Pweave matplotlib metys)
pip3 install --upgrade pip setuptools wheel
if [[ "${TRAVIS_OS_NAME:-}" == "linux" ]]; then
  pip3 install --user ${PIP_MODULES[*]}
else
  pip3 install ${PIP_MODULES[*]}
fi

if ! Rscript -e "library(knitr);library(patchSynctex)" &> /dev/null; then
  echo Installing R libraries...
  mkdir -p "${R_LIBS_USER}"
  Rscript -e "install.packages(c('knitr','patchSynctex'),repos='http://cran.r-project.org')"
else
  echo Using cached R libraries
fi

if [[ "${TRAVIS_OS_NAME:-}" == "osx" ]]; then
  pweave --output=foo.tex packages/core/spec/fixtures/builder-tests/test-pweave.Pnw
fi
