#!/usr/bin/env bash

shopt -s nocasematch

if [[ "${APPVEYOR:-}" == true ]]; then
  echo Installing node...
  PowerShell -Command Install-Product node 7 x64

  echo Installing GhostScript...
  cinst ghostscript

  echo Installing Agda and lhs2TeX...
  curl -sS -ostack.exe -L --insecure http://www.stackage.org/stack/windows-x86_64-installer
  stack setup > nul
  stack update
  cabal install Agda lhs2tex

  echo Installing R...
  cinst R.Project --allow-empty-checksums --ia="/DIR=\"${R_HOME}\""

  echo Installing MikTeX...
  cinst miktex

  echo Installing TeX packages...
  initexmf --set-config-value=[MPM]AutoInstall=0
  mpm --admin --install-some=scripts\\miktex-packages
  initexmf --admin --update-fndb

  echo Installing package dependencies...
  npm install
elif [[ "${TRAVIS_OS_NAME:-}" == "osx" ]]; then
  export PATH=/Library/TeX/texbin:~/Library/Haskell/bin:$PATH

  echo Updating homebrew...
  brew update

  echo Installing Python 3...
  brew install python3
  virtualenv venv -p python3
  source venv/bin/activate

  echo Installing GhostScript...
  brew install ghostscript

  echo Installing Agda and lhs2TeX...
  brew cask install haskell-platform
  stack update
  sudo cabal install Agda lhs2tex

  echo Installing R...
  brew tap homebrew/science
  brew install r

  echo Installing MacTeX...
  wget http://tug.org/cgi-bin/mactex-download/BasicTeX.pkg
  sudo installer -pkg BasicTeX.pkg -target /

  echo Installing TeX packages...
  sudo tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
  sudo tlmgr update --self
  sudo tlmgr update --all
  cat "scripts/mactex-packages" | xargs sudo tlmgr install
fi

echo Installing Python libraries...
pip3 install Pygments Pweave matplotlib

if ! Rscript -e "library(knitr);library(patchSynctex)" &> /dev/null; then
  echo Installing R libraries...
  mkdir -p "${R_LIBS_USER}"
  Rscript -e "install.packages(c('knitr', 'patchSynctex'), repos = 'http://cran.r-project.org')"
else
  echo Using cached R libraries
fi
