#!/usr/bin/env bash

shopt -s nocasematch

echo Installing Pygments...
pip2 install Pygments
pip3 install Pygments

echo Installing Pweave...
pip2 install Pweave matplotlib

if [[ "${APPVEYOR:-}" == true ]]; then
  echo Installing node...
  PowerShell -Command Install-Product node 7 x64

  echo Installing GhostScript...
  cinst ghostscript

  echo Installing R...
  cinst R.Project --allow-empty-checksums --ia="/DIR=\"${R_HOME}\""

  echo Installing MikTeX...
  cinst miktex

  echo Installing TeX packages...
  initexmf --set-config-value=[MPM]AutoInstall=0
  mpm --admin --install-some=scripts\\miktex-packages
  initexmf --admin --update-fndb

  echo Installing package dependencies...
  npm install
elif [[ "${TRAVIS_OS_NAME:-}" == "osx" ]]; then
  echo Updating homebrew...
  brew update

  echo Installing GhostScript...
  brew install ghostscript

  echo Installing lhs2TeX...
  brew cask install haskell-platform
  stack update
  sudo cabal install lhs2tex

  echo Installing R...
  brew tap homebrew/science
  brew install r

  echo Installing MacTeX...
  wget http://tug.org/cgi-bin/mactex-download/BasicTeX.pkg
  sudo installer -pkg BasicTeX.pkg -target /

  echo Installing TeX packages...
  sudo tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
  sudo tlmgr update --self
  sudo tlmgr update --all
  cat "`dirname $0`/mactex-packages" | xargs sudo tlmgr install
fi

if ! Rscript -e "library(knitr);library(patchSynctex)" &> /dev/null; then
  echo Installing R libraries...
  mkdir -p "${R_LIBS_USER}"
  Rscript -e "install.packages(c('knitr', 'patchSynctex'), repos = 'http://cran.r-project.org')"
else
  echo Using cached R libraries
fi
