#!/usr/bin/env bash

cd packages/core/spec/fixtures

echo Creating log files...

pdflatex -file-line-error -interaction=batchmode error-warning.tex &>/dev/null
rm error-warning.aux

cd file-types

echo Creating Knitr files...
Rscript -e "library(knitr);opts_knit\$set(concordance=TRUE);knit('RNoWeb.Rnw')" &>/dev/null
rm -rf RNoWeb.tex figure
mv RNoWeb-concordance.tex KnitrConcordance-concordance.tex

echo Creating LaTeX files...
mkdir output
latex -jobname=biber -interaction=batchmode -recorder -output-directory=output -synctex=1 LaTeX_article.tex &>/dev/null
biber output/biber.bcf &>/dev/null
xdvipdfmx -o PortableDocumentFormat.pdf output/biber.dvi &>/dev/null
dvips -o PostScript.ps output/biber.dvi &>/dev/null
cp output/biber.acn AcronymControlFile.acn
cp output/biber.aux LaTeXAuxilary.aux
cp output/biber.bcf BiberControlFile.bcf
cp output/biber.bdx BibRefControlFile.bdx
cp output/biber.blg BiberLog.blg
cp output/biber.dvi DeviceIndependentFile.dvi
cp output/biber.fls FileListing.fls
cp output/biber.glo GlossaryControlFile.glo
cp output/biber.idx IndexControlFile.idx
cp output/biber.ist IndexStyleFile.ist
cp output/biber.log LaTeXLog_pdfTeX.log
cp output/biber.nlo NomenclatureControlFile.nlo
cp output/biber.pytxcode PythonTeX.pytxcode
cp output/biber.sagetex.sage Sage.sage
cp output/biber.synctex.gz SyncTeX.synctex.gz

rm -rf output

cd ../builder-tests

for file in {*.tex,*.lhs,*.lagda,*.Rnw,*.Pnw}; do
  echo "Creating event archive for $file"
  node ../../../../cli/lib/main.js bl --save-events=command,log --ignore-user-options "$file" &>/dev/null
  node ../../../../cli/lib/main.js s --ignore-user-options "$file" &>/dev/null
done
