#!/usr/bin/env bash

if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  echo Updating homebrew...
  brew update

  echo Installing GhostScript...
  brew install ghostscript

  echo Installing lhs2TeX...
  brew cask install haskell-platform
  stack update
  sudo cabal install lhs2tex

  echo Installing R...
  brew tap homebrew/science
  brew install r

  echo Installing Pygments...
  pip install Pygments

  echo Installing MacTeX...
  wget http://tug.org/cgi-bin/mactex-download/BasicTeX.pkg
  sudo installer -pkg BasicTeX.pkg -target /

  echo Installing TeX packages...
  sudo tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
  sudo tlmgr update --self
  sudo tlmgr update --all
  sudo cat "`dirname $0`/mactex-packages" | xargs tlmgr install 
fi
