#!/usr/bin/env bash

if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  echo Updating homebrew...
  time brew update

  echo Installing GhostScript...
  time brew install ghostscript

  echo Installing lhs2TeX...
  time brew cask install haskell-platform
  time stack update
  time sudo cabal install lhs2tex

  echo Installing R...
  time brew tap homebrew/science
  time brew install r

  echo Installing Pygments...
  time pip install Pygments

  echo Installing MacTeX...
  time wget http://tug.org/cgi-bin/mactex-download/BasicTeX.pkg
  time sudo installer -pkg BasicTeX.pkg -target /

  echo Installing TeX packages...
  time sudo tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
  time sudo tlmgr update --self
  time sudo tlmgr update --all
  time sudo tlmgr install \
    adjustbox \
    amsrefs \
    asymptote \
    biber \
    biblatex \
    bibtopic \
    collectbox \
    currfile \
    datatool \
    everypage \
    filemod \
    framed \
    fvextra \
    gincltex \
    glossaries \
    ifplatform \
    lazylist \
    lipsum \
    logreq \
    makeglos \
    mfirstuc \
    minted \
    multibib \
    nomencl \
    polytable \
    standalone \
    stmaryrd \
    subfiles \
    substr \
    supertabular \
    svn-prov \
    texware \
    ucs \
    xfor \
    xstring
fi
