#!/usr/bin/bash

TEX_PACKAGES=(
  amsrefs
  asymptote
  biber
  bibtopic
  currfile
  datatool
  filemod
  fvextra
  gincltex
  glossaries
  ifplatform
  index
  lazylist
  makeglos
  mfirstuc
  minted
  multibib
  nomencl
  polytable
  standalone
  subfiles
  substr
  supertabular
  svn-prov
  texware
  xfor
)

if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  sudo tlmgr install ${TEX_PACKAGES[*]}
else
  tlmgr install ${TEX_PACKAGES[*]}
fi

npm install
npm run update-dependencies
npm run bootstrap
