## -*- encoding: utf-8 -*-
## This file (biber.sagetex.sage) was *autogenerated* from biber.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('biber', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = 41
_st_.blockbegin()
try:
   f(x) = cos(x) * exp(x)
except:
 _st_.goboom(43)
_st_.blockend()
_st_.endofdoc()
