/* @flow */

import Rule from '../Rule'

import type { CommandOptions, Phase } from '../types'

function escapePath (filePath) {
  return filePath.replace(/\\/g, '\\\\')
}

export default class PatchSyncTeX extends Rule {
  static parameterTypes: Array<Set<string>> = [
    new Set(['Knitr']),
    new Set(['SyncTeX']),
    new Set(['KnitrConcordance'])
  ]
  static phases: Set<Phase> = new Set(['finalize'])
  static description: string = 'Patches SyncTeX files if LaTeX document was generated by knitr so PDF reverse sync will work.'

  constructCommand (): CommandOptions {
    const filePath = escapePath(this.firstParameter.filePath)
    // Remove the SyncTeX extensions because patchSynctex tries to guess it.
    const synctexPath = escapePath(this.secondParameter.filePath.replace(/\.synctex(\.gz)?$/i, ''))
    const lines = [
      'library(patchSynctex)',
      `patchSynctex('${filePath}',syncfile='${synctexPath}')`]

    // Set the severity to warning since patching the SyncTeX file is just a
    // nicety.
    return {
      args: ['Rscript', '-e', lines.join(';')],
      cd: '$ROOTDIR',
      severity: 'warning',
      outputs: ['$DIR_1/BASE_1']
    }
  }
}
