import Rule from '../Rule'
import { CommandOptions, Phase } from '../types'

function escapePath (filePath: string): string {
  return filePath.replace(/\\/g, '\\\\')
}

export default class PatchSyncTeX extends Rule {
  static parameterTypes: Set<string>[] = [
    new Set(['KnitrConcordance']),
    new Set(['SyncTeX'])
  ]
  static phases: Set<Phase> = new Set<Phase>(['finalize'])
  static description: string = 'Patches SyncTeX files if LaTeX document was generated by knitr so PDF reverse sync will work.'

  constructCommand (): CommandOptions {
    // Remove the concordance part of the file name because patchSynctex just
    // adds it back on. The first parameter is really supposed to be the Rnw
    // file, but patchSynctex has no way to know the output path of knit if
    // it is a custom value. If we pass the root name of the concordance file
    // then we can trick it into customizing the name.
    const filePath = escapePath(this.firstParameter.filePath.replace('-concordance', ''))
    // Remove the SyncTeX extensions because patchSynctex tries to guess it.
    const synctexPath = escapePath(this.secondParameter.filePath.replace(/\.synctex(\.gz)?$/i, ''))
    const lines = [
      'library(patchSynctex)',
      `patchSynctex('${filePath}',syncfile='${synctexPath}')`]

    // Set the severity to warning since patching the SyncTeX file is just a
    // nicety.
    return {
      args: ['Rscript', '-e', lines.join(';')],
      cd: '$ROOTDIR',
      severity: 'warning',
      outputs: [{ file: '$DIR_1/BASE_1' }]
    }
  }
}
